---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language: node
polling_url: ''
polling_headers: ''
polling_body: ''
id: 314111
custom_fields:
- keyname: doesnt_matter
  name: About This Plugin
  category: life,productivity
  field_type: author_bio
  description: Shows shopping list in TRMNL
  learn_more_url: https://culturedcode.com/things/
  email_address: charlie@evilforbeginners.com
- keyname: lines_title
  name: Maximum Lines Title
  description: 0 = No limit
  field_type: number
  group: Display Options
  default: 2
  min: 0
  max: 6
- keyname: lines_description
  name: Maximum Lines Description
  description: 0 = No limit, -1 = Always Hide description
  field_type: number
  group: Display Options
  default: 2
  min: -1
  max: 6
- keyname: show_progress
  name: Show Progress Dots
  field_type: boolean
  group: Display Options
  default: true
name: Shopping List
refresh_interval: 15
